<?xml version="1.0"?>
<package format="3">
  <name>my_robot_controller</name>
  <version>0.0.1</version>
  <description>A simple robot controller for ROS 2.</description>

  <maintainer email="xmtang1@myseneca.ca">Xiao Ming Tang</maintainer>
  <license>BSD</license>
  <author email="xmtang1@myseneca.ca">Xiao Ming Tang</author>

  <!-- Use ament_python as the build tool -->
  <buildtool_depend>ament_python</buildtool_depend>
  <build_depend>rclpy</build_depend>
  <exec_depend>rclpy</exec_depend>

  
  <!-- Adding geometry_msgs as both build and exec dependency -->
  <build_depend>geometry_msgs</build_depend>
  <exec_depend>geometry_msgs</exec_depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
