<?xml version="1.0"?>
<package format="3">
  <name>my_robot_controller</name>
  <version>0.0.1</version>
  <description>A simple robot controller for ROS 2.</description>

  <maintainer email="xmtang1@myseneca.ca">Xiao Ming Tang</maintainer>
  <license>BSD</license>

  <author email="xmtang1@myseneca.ca">Xiao Ming Tang</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclpy</build_depend>
  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
